name: nba_stats_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.18.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  shared_preferences: ^2.1.2

dev_dependencies:
  fl_chart: ^0.62.0
  flutter_animator: ^3.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  syncfusion_flutter_charts: ^21.1.41

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/teams.json

  fonts:
    - family: Helvatica
      fonts:
        - asset: assets/fonts/helvatica-neue/regular.ttf
        - asset: assets/fonts/helvatica-neue/medium.ttf
        - asset: assets/fonts/helvatica-neue/bold.ttf
